[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"
  environment = { SECRETS_SCAN_ENABLED = "false" }

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"